export type GameItemCategory = "quest" | "collectible" | "cosmetic" | "character";

export type GameItem = {
  id: string;
  name: string;
  description: string;
  category: GameItemCategory;
  image: string;
  purchasable: boolean;
  price: number;
  stackable: boolean;
  consumable: boolean;
  usableInQuests: boolean;
};

export const GAME_ITEMS: GameItem[] = [
  {
    id: "flashlight",
    name: "Flashlight",
    description: "Useful for dark quest paths.",
    category: "quest",
    image: "/quests/items/flashlight.png",
    purchasable: true,
    price: 10,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "rope",
    name: "Rope",
    description: "Lets you anchor risky quest routes.",
    category: "quest",
    image: "/quests/items/rope.png",
    purchasable: true,
    price: 12,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "snack-pack",
    name: "Snack Pack",
    description: "A quick snack for hungry quest allies.",
    category: "quest",
    image: "/quests/items/snack-pack.png",
    purchasable: true,
    price: 8,
    stackable: true,
    consumable: true,
    usableInQuests: true,
  },
  {
    id: "spare-button",
    name: "Spare Button",
    description: "A tiny trinket for polite quest diplomacy.",
    category: "quest",
    image: "/quests/items/spare-button.png",
    purchasable: true,
    price: 6,
    stackable: true,
    consumable: true,
    usableInQuests: true,
  },
  {
    id: "broom",
    name: "Broom",
    description: "Clears lint and opens tidy routes.",
    category: "quest",
    image: "/quests/items/broom.png",
    purchasable: true,
    price: 14,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "clothespins",
    name: "Clothespins",
    description: "Stabilize cloth bridges and hanging paths.",
    category: "quest",
    image: "/quests/items/clothes-pins.png",
    purchasable: true,
    price: 7,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "magnet",
    name: "Magnet",
    description: "Pulls metal zippers and hidden latches.",
    category: "quest",
    image: "/quests/items/magnet.png",
    purchasable: true,
    price: 11,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "paper-map",
    name: "Paper Map",
    description: "Tracks winding paths in quest worlds.",
    category: "quest",
    image: "/quests/items/paper-map.png",
    purchasable: true,
    price: 9,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "gloves",
    name: "Gloves",
    description: "Protect your hands from static tunnels.",
    category: "quest",
    image: "/quests/items/gloves.png",
    purchasable: true,
    price: 9,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "tiny-key",
    name: "Tiny Key",
    description: "A special key granted by quest allies.",
    category: "quest",
    image: "/quests/items/tiny-key.png",
    purchasable: true,
    price: 15,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "laundry-basket",
    name: "Laundry Basket",
    description: "Carries piles of rescued socks.",
    category: "quest",
    image: "/quests/items/laundry-basket.png",
    purchasable: true,
    price: 13,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "magic-thread",
    name: "Magic Thread",
    description: "Links separated places with one stitch.",
    category: "quest",
    image: "/quests/items/magic-thread.png",
    purchasable: true,
    price: 16,
    stackable: true,
    consumable: true,
    usableInQuests: true,
  },
  {
    id: "whistle",
    name: "Whistle",
    description: "Calls lost allies from far away.",
    category: "quest",
    image: "/quests/items/whistle.png",
    purchasable: true,
    price: 10,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "sorting-cards",
    name: "Sorting Cards",
    description: "Speeds up sorting and pairing puzzles.",
    category: "quest",
    image: "/quests/items/sorting-cards.png",
    purchasable: true,
    price: 12,
    stackable: false,
    consumable: false,
    usableInQuests: true,
  },
  {
    id: "character_default_avatar_01",
    name: "Pip the Portal Pal",
    description: "Unlocked by completing the first quest.",
    category: "character",
    image: "/avatars/default/avatar-01.png",
    purchasable: false,
    price: 0,
    stackable: false,
    consumable: false,
    usableInQuests: false,
  },
  {
    id: "golden-laundry-token",
    name: "Golden Laundry Token",
    description: "A rare collectible from the Sock Kingdom.",
    category: "collectible",
    image: "/assets/items/golden-laundry-token.png",
    purchasable: false,
    price: 0,
    stackable: false,
    consumable: false,
    usableInQuests: false,
  },
  {
    id: "striped-sock-badge",
    name: "Striped Sock Badge",
    description: "Proof that you guided every sock home.",
    category: "collectible",
    image: "/assets/items/striped-sock-badge.png",
    purchasable: false,
    price: 0,
    stackable: false,
    consumable: false,
    usableInQuests: false,
  },
  {
    id: "sock-portal-master-badge",
    name: "Sock Portal Master Badge",
    description: "Awarded for discovering every ending.",
    category: "collectible",
    image: "/assets/items/sock-portal-master-badge.png",
    purchasable: false,
    price: 0,
    stackable: false,
    consumable: false,
    usableInQuests: false,
  },
];

export const GAME_ITEM_BY_ID = new Map(GAME_ITEMS.map((item) => [item.id, item]));

export function findGameItemById(itemId: string) {
  return GAME_ITEM_BY_ID.get(itemId) ?? null;
}

export function listPurchasableQuestItems() {
  return GAME_ITEMS.filter((item) => item.category === "quest" && item.purchasable);
}
